use SisFacturacion;

CREATE TABLE ROLES(
IDROLE INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_ROL VARCHAR(50),
DESCRIPCION VARCHAR(500),
ESTADO INT CHECK(ESTADO IN (1,2,3))
);



INSERT INTO ROLES (NOMBRE_ROL, ESTADO) VALUES('USUARIO FINAL',1);
INSERT INTO ROLES (NOMBRE_ROL, ESTADO) VALUES('SOPORTE TECNICO',1);
INSERT INTO ROLES (NOMBRE_ROL, ESTADO) VALUES('SUPERVISOR',1);
INSERT INTO ROLES (NOMBRE_ROL, ESTADO) VALUES('ADMINISTRADOR',1);

SELECT * FROM ROLES;

CREATE TABLE OPCIONES_X_ROL(
IDROLE INT NOT NULL,
IDOPCION VARCHAR(50) NOT NULL,
PRIMARY KEY (IDROLE, IDOPCION),
FOREIGN KEY (IDROLE) REFERENCES ROLES (IDROLE)
);

CREATE TABLE PRODUCTOS(
NOMBREPROD VARCHAR(50) NOT NULL,
CANTIDADPROD INT NOT NULL,
CODIGOPROD INT NOT NULL,
PRECIOPROD FLOAT NOT NULL,
IDPRODUCTO INT PRIMARY KEY IDENTITY (01,01),
);

CREATE TABLE PRODCATEGORIAS(
IDCATEGORIA INT DEFAULT 1,
NOMBRE_CATEGORIA VARCHAR(50) NOT NULL,
DESCRIPCION_CATEGORIA VARCHAR (50) NOT NULL,
);

CREATE TABLE DETALLES(
ID_FACTURA INT PRIMARY KEY IDENTITY (1,1),
CANTIDAD INT NOT NULL,
PRECIO INT NOT NULL,
);


CREATE TABLE FACTURAS(
NUM_FACTURA INT PRIMARY KEY IDENTITY (1,1),
FECHA DATETIME DEFAULT GETDATE(),
NUM_PAGO INT DEFAULT 1,
);


CREATE TABLE VENDEDOR(
IDVENDEDOR INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(50) NOT NULL UNIQUE,
CLAVE VARCHAR(50) NOT NULL DEFAULT '12345',
IDROLE INT DEFAULT 1,
ESTADO VARCHAR(15) CHECK( ESTADO IN ('ACTIVO','INACTIVO','BLOQUEADO', 'SUSPENDIDO')),
FECHA_CREACION DATETIME DEFAULT GETDATE(),
FOREIGN KEY (IDROLE) REFERENCES ROLES (IDROLE)
);

CREATE TABLE CICLO (
ID_CICLO INT NOT NULL,
NUMERO_CICLO INT NOT NULL,
FECHA_INICIO DATETIME DEFAULT GETDATE(),
FECHA_FINAL DATETIME DEFAULT GETDATE(),
);




INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(1,'INICIO');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(1,'CONSULTA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(1,'AYUDA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(1,'FACTURAR');

INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(2,'INICIO');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(2,'CONSULTA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(2,'AYUDA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(2,'CONFIGURACION');

INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(3,'INICIO');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(3,'CONSULTA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(3,'AYUDA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(3,'MANTENIMIENTO');

INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(4,'INICIO');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(4,'AYUDA');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(4,'CONFIGURACION');
INSERT INTO OPCIONES_X_ROL (IDROLE,IDOPCION) VALUES(4,'ADMINISTRACION');

SELECT * FROM OPCIONES_X_ROL

CREATE TABLE USUARIOS(
IDUSUARIO INT PRIMARY KEY IDENTITY(1,1),
USUARIO VARCHAR(50) NOT NULL UNIQUE,
CLAVE VARCHAR(50) NOT NULL DEFAULT '12345',
IDROLE INT DEFAULT 1,
ESTADO VARCHAR(15) CHECK( ESTADO IN ('ACTIVO','INACTIVO','BLOQUEADO', 'SUSPENDIDO')),
FECHA_CREACION DATETIME DEFAULT GETDATE(),
FOREIGN KEY (IDROLE) REFERENCES ROLES (IDROLE)
);

INSERT INTO USUARIOS (USUARIO) VALUES('ANGEL');
INSERT INTO USUARIOS (USUARIO) VALUES('ADON');
INSERT INTO USUARIOS (USUARIO, IDROLE ) VALUES('SOPORTE TECNICO',2);
INSERT INTO USUARIOS (USUARIO, IDROLE) VALUES('AADON',3);
INSERT INTO USUARIOS (USUARIO, CLAVE, IDROLE) VALUES('ADMIN','ADMIN',4);

SELECT * FROM USUARIOS

SELECT A.USUARIO, A.CLAVE , A.IDROLE, B.IDOPCION FROM USUARIOS A , OPCIONES_X_ROL B
WHERE A.IDROLE = B.IDROLE

CREATE VIEW V_PERMISOS
AS
SELECT A.USUARIO, A.CLAVE, A.IDROLE, B.IDOPCION
FROM dbo.USUARIOS AS A INNER JOIN
dbo.OPCIONES_X_ROL AS B ON A.IDROLE = B.IDROLE;

SELECT * FROM V_PERMISOS;